import type { Metadata } from 'next';
import { lato } from '@/lib/utils';

import './globals.css';
import { Footer, Header } from '@/modules';

export const metadata: Metadata = {
  title: 'Org Vista',
  description: 'Generated by Org Vista',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.className} dark antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
